# Generated by Django 2.1.4 on 2018-12-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeStartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemachine',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
